### ISSUE TITLE
Add missing documentation

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/Magpie#332]
Following magpie features have no explicit mention or setup details. Relevant sections should be created so that they can be found by new users.

- [x] resource auto-sync feature for a given service and cron configuration setup for it (fixed by 29b907f111d2d44a9f1b0985397c68bbe05ebff2)
- [x] listing and explanation/features of every available service types (fixed by 29b907f111d2d44a9f1b0985397c68bbe05ebff2)
- [x] explicit description of user/group vs service/resource objects and their relationships
- [x] description of flags that modify request results (effective, inherited, cascade, list) (see descriptions in #341)
- [x] distinction between different kind of *permissions*: 
    - *applied permissions* : entry for a given service/resource-user/group combination
    - *effective permissions*: resolution of *applied permissions* of user & his group membership
    - *access permissions*: allowed level to routes to request details (ie: roles)   (wip #340) 
    - *ownership permissions*: extra set of permissions to user/group that owns the service/resource   (?) 
      (provides *access permissions* to some specific routes matching the service/resource & provide all *applied permissions* for it)
- [x] distinction of *applied permission* modifiers (#342): 
    - *match* vs *recur* 
        - *recur*: recursive to this and all children resources: (implicit for backward compat when no modifier provided)
        - *match*: only applied onto this specific resource
    - *allow* vs *deny* (#235) 
        - *allow*: default when permission is added (for backward compat)
        - *deny*: explicit override of any previous 'allow' (including recursive of parent resource, no permission equals deny) 
- [x] ~AuthN details~ refer to specific issue (#344)
