### ISSUE TITLE
Fetch Existing Service Resources to Populate Magpie Permissions

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/Magpie#42]
# details
## Potential services to fetch: 
- geoserver 'workspaces' (projects, see Ouranosinc/Magpie#39) 
- thredds (datasets, see Ouranosinc/Magpie#41)
- ... 

## Questions to consider : 
- should Magpie 'automatically' trigger fetches (risk of removing perms if service is removed somewhere at the wrong moment)
- should Magpie UI have a button to trigger a fetch (force)
- ...

Full Details: [here](https://www.crim.ca/confluence/pages/viewpage.action?pageId=21760512)

# planning

## todo
- [ ] warning flag on non-existing resource between db & actual service (on each tree-line)
- [ ] update flags on user (with admin perms) goto page of service to fetch
- [ ] ask `remove all warnings` or cancel for user to remove resources one by one
- [ ] button to re-send the `remove all warnings` command (if any)
- [ ] if no permission is associated with a dangling resource, delete it immediately (no confirm required)
- [ ] if permissions are associated to a dangling resource, require user confirmation

![image](https://user-images.githubusercontent.com/19194484/40435768-68bdea22-5e7f-11e8-82a2-e592ae490e67.png)

**Comment by fmigneault** [comment]
relates to Ouranosinc/Magpie#44

**Comment by Zvax** [comment]
This might be a good moment to see what granularity is desired for geopackages (and shapefiles, and other shape formats). For instance, could we want to allow access to a specific geopackage, but not to all of its containing workspace?

This can have impact on what there is to fetch.

**Comment by fmigneault** [comment]
@Zvax 
For now, geoserver-api is setup to block specific routes.
So if workspace contents are accessed via something like `/workspaces/{the_thing}`, it should be possible to block very granular accesses.
I'm not sure about the geopackage content though.
From my understanding, the SQLite sub-format would require another access control approach, unless all of these contents are accessible via geoserver api routes?

**Comment by Zeitsperre** [comment]
Not sure if it's helpful, but some of the work being done at Ouranos is looking into ways of iterating over GeoPackage contents so that they can be uploaded and published to a GeoServer workspace. We're using a fairly old tool (https://github.com/boundlessgeo/gsconfig) with its limitations, but there might be some useful examples of how the GeoServer API work within the source code.

**Comment by dbyrns** [comment]
For geoserver, the list of workspaces can be retrieved like this : http://docs.geoserver.org/latest/en/api/#/1.0.0/workspaces.yaml
Other reference : https://www.crim.ca/jira/browse/PAV-501

For Project-API, the api is available here:
https://github.com/Ouranosinc/PAVICS-project-api/issues/10
