### ISSUE TITLE
Generic Service for Route/Provider Access 

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/Magpie#71]
## TODO
- [x] All services registered under the new service type with different server routes similarly to WPS (flyingpigeon, malleefowl, etc.)
- [x] Services access validated per user permission
- [ ] Services registered under providers automatically (ref issue #58)

## Reason
- Allow registering `PAVICS-frontend`, `geoserver/web`, `Magpie` or any other top-level route 
- Needed to fully move routes behind `Twitcher`

**Comment by fmigneault** [comment]
done steps references #75 #76 
last step duplicated by #58
