### ISSUE TITLE
Unittests

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/Magpie#74]
**Check/validate functionalities added/adjusted in following cases:**

- [x] PR #72 (default users, groups and services properly registered after start)
- [x] PR #73 (`/services` routes with `permission_names` listing applicable permissions)
- [x] cover most critical routes used by PAVICS frontend
- [x] `/users` routes
- [x] `/groups` routes
- [x] `/resources` routes
- [x] `/services` routes
- [x] inputs validation (see #84)
- [x] new features from PR #104
- [x] new features from PR #109 
- [x] test that validates #158 (do for both delete/create functions)
- [x] tests for `inherit` query flag on all applicable routes
- [x] tests for `cascade` query flag on all applicable routes
- [x] tests for `effective` query flag on all applicable routes (PR #135)
- [x] tests for `register` operations
- [x] tests for CLI helpers (relates to PR #339)
- [x] tests for `MagpieAdapter` (some introduced by PR #353, but not everything is covered)
      ~tests of basic functionality of MagpieAdapter for Twitcher (see issue #130)~
